[package]
name = "cef-sys"
version = "0.1.0"
authors = ["Max Froehlich <max@mfro.me>"]
edition = "2018"
links = "cef"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
